config/routes.rb
Rails.application.routes.draw do
  
  resources :projects do
      resources :subprojects
  end
  devise_for :users, controllers: { sessions: "sessions" }
  
  root to: "pages#index"
  get "people" => "pages#people"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :user
	has_many :subprojects, dependent: :destroy
end

app/models/subproject.rb
class Subproject < ApplicationRecord
	belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects, dependent: :destroy


  after_create :create_project_and_subproject

  def create_project_and_subproject
    project = Project.create(user: self, project_name: "Getting Started")
    project.subprojects.create(subproject_name: "Here are the basics")    
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_sign_in_path_for(resource)
		user = current_user
		if user
		  last_viewed_project_id = user.last_viewed_project_id
		  if last_viewed_project_id
		    project = resource.projects.find_by(id: last_viewed_project_id)
		    if project
		      project_path(project)
		    else
		      project_path(current_user.projects.first.id)
		    end
		  else
		    project_path(current_user.projects.first.id)
		  end
		else
		  super
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  
  def index
    if user_signed_in?
      @project_sidebar = current_user.projects.all.order("created_at ASC")
    end
  end

  def people
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
    @project_sidebar = current_user.projects.all.order("created_at ASC")
  end

  # GET /projects/1 or /projects/1.json
  def show
    @project_sidebar = current_user.projects.all.order("created_at ASC")

    session[:last_viewed_project_id] = params[:id]
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:project_name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  before_action :set_last_viewed_project_id, only: [:destroy]

  private

  def set_last_viewed_project_id
    # Set the last viewed project ID on the user
    current_user.update(last_viewed_project_id: session[:last_viewed_project_id])
  end
end

app/controllers/subprojects_controller.rb
class SubprojectsController < ApplicationController
  before_action :set_subproject, only: %i[ show edit update destroy ]
  before_action :set_project, only: [:show, :edit, :update, :create, :new, :destroy]


  # GET /subprojects or /subprojects.json
  def index
    @subprojects = current_user.subprojects
  end

  # GET /subprojects/1 or /subprojects/1.json
  def show
  end

  # GET /subprojects/new
  def new
    @subproject = @project.subprojects.new
  end

  # GET /subprojects/1/edit
  def edit
  end

  # POST /subprojects or /subprojects.json
  def create
    @subproject = @project.subprojects.build(subproject_params)

    respond_to do |format|
      if @subproject.save
        format.html { redirect_to @subproject.project, notice: "Subproject was successfully created." }
        format.json { render :show, status: :created, location: @subproject }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subproject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subprojects/1 or /subprojects/1.json
  def update
    respond_to do |format|
      if @subproject.update(subproject_params)
        format.html { redirect_to @subproject.project, notice: "Subproject was successfully updated." }
        format.json { render :show, status: :ok, location: @subproject }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subproject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subprojects/1 or /subprojects/1.json
  def destroy
    @subproject.destroy

    respond_to do |format|
      format.html { redirect_to subprojects_url, notice: "Subproject was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subproject
      @subproject = Subproject.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Only allow a list of trusted parameters through.
    def subproject_params
      params.require(:subproject).permit(:subproject_name, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/subprojects_helper.rb
module SubprojectsHelper
end

app/views/application/_basic_layout.html.erb
<% if current_user %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %>
  <%= yield :side_navbar %>
  <%= yield :project_content  %>
  <%= yield :content_list  %>

<% else %>
  <%= render partial: "pages/index" %>
<% end %>

app/views/application/_project_content.html.erb
<!-- Project content -->
<div class="flex-1 flex flex-col bg-white overflow-hidden">
    <!-- Top bar -->
    <div class="border-b flex px-12 mt-4 flex-none">
        <div class=" flex justify-between">
            <!--sub navbar -->
            <div class=" inline-flex justify-center">
              <ul class="flex justify-between sm:flex-row space-x-2">
                <li class="cursor-pointer flex items-center block py-1 font-semibold border-b-2 border-gray-800 text-gray-600 no-underline hover:text-gray-800 focus:outline-none ">
                  <a id="#first" href="#first" class="no-underline">Subprojects</a>
                </li>
                <li class="cursor-pointer flex items-center block px-2 py-1 font-medium border-gray-800 text-gray-500 no-underline hover:text-gray-800 focus:outline-none ">
                  <a id="#second" href="#first" class="no-underline">People</a>
                </li>
                <li class="cursor-pointer flex items-center block px-2 py-1 font-medium border-gray-800 text-gray-500 no-underline hover:text-gray-800 focus:outline-none ">
                  <a id="#second" href="#first" class="no-underline">Groups</a>
                </li>
              </ul>
            </div>           
        </div>
        <div class="ml-auto hidden md:block">

        </div>
    </div>
    <!-- Content -->
    <div class="px-2 py-4 flex-1 overflow-y-scroll">
        <%= render @project.subprojects %>
    </div>
    <!-- Subproject form -->
    <div class="pb-6 pl-12 pr-2 flex-none mt-4">
        <div class="flex rounded-lg border-2 border-grey overflow-hidden">
            <div class="focus:outline-none py-2">
                <input class="w-full px-4 focus:outline-none mb-4" placeholder="Subproject name" />
                <!-- <input type="text" class="w-full px-4 focus:outline-none mb-4" placeholder="Description" /> -->
                <!-- <input type="search" placeholder="Search" class="ml-4 appearance-none border focus:outline-none border-grey rounded-lg pr-4 py-2"> -->
            </div>
        </div>
    </div>
</div>

app/views/application/_side_navbar.html.erb
<!-- component -->
<div class="font-sans antialiased h-screen flex">
    <div class="bg-gray-50 text-purple-lighter flex-none w-62 pb-6 hidden md:block border-r">
        <div class="mb-2 flex justify-between">
            <div class="flex-auto">
                <div class="flex">
                    <div x-data="{ dropdownOpen: false }" class="relative">
                        <button @click="dropdownOpen = !dropdownOpen" class="relative py-2 px-6 text-gray-800 hover:bg-gray-200 focus:outline-none focus:bg-gray-400">
                            <h1 class="font-semibold text-xl leading-tight truncate">Anthony's Workspace</h1>
                        </button>

                    <div x-show="dropdownOpen" @click="dropdownOpen = false" class="fixed inset-0 z-10 w-full h-full"></div>

                        <div x-show="dropdownOpen" class="absolute right-0 z-20 w-11/12 mt-2 overflow-hidden bg-white rounded-md shadow-xl">
                            <%= link_to "Account", edit_user_registration_path, class: "block px-6 py-2 text-sm text-gray-800 hover:bg-gray-200" %>
                            
                            <%= button_to destroy_user_session_path, method: :delete, class: "px-12 " do %>
                                <span class="block py-2 text-sm text-gray-800 hover:bg-gray-200">Logout </span>
                            <% end %>
                            <%#= link_to "Link Sign out rails-ujs and Turbo", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: "block px-6 py-2 text-sm text-gray-800 hover:bg-gray-200" %>

                            <%= link_to "Sign out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %>
                        </div>
                    </div>
                </div>

                <div class="mb-6 px-6">
                    <span class="bg-green rounded-full block w-2"></span>
                    <span class=" opacity-50 text-sm">Settings & members</span>
                </div>
            </div>
            <div>
            </div>
        </div>
        <div class="mb-8">
            <div class="px-6 mb-2 flex justify-between items-center">
                <div class="opacity-75">Projects</div>
                <div>
                    <svg class="fill-current h-4 w-4 opacity-50" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                        <path d="M11 9h4v2h-4v4H9v-4H5V9h4V5h2v4zm-1 11a10 10 0 1 1 0-20 10 10 0 0 1 0 20zm0-2a8 8 0 1 0 0-16 8 8 0 0 0 0 16z" />
                    </svg>
                </div>
            </div>
            <div class="flex flex-col">
                <%#= render @project_sidebar %>

                <%#= render partial: 'projects/projects_sidebar', :project => @project %>

                <% @project_sidebar.each do |project| %>
                    <%= link_to project do %>

                            <div class="flex bg-teal-dark py-1 px-6 hover:bg-gray-200 justify-between hover-trigger">
                                <div>
                                    <%= project.project_name %>
                                </div>
                                <div class="hover-target relative flex items-center justify-center flex-shrink-0 w-6 h-6 overflow-hidden bg-gray-50 rounded hover:bg-gray-200">
                                    <i class="fa fa-light fa-ellipsis fa-sm"></i>
                                </div>
                            </div>
                    <% end %>
                <% end %>
            </div>
   	    </div>

<style>
.hover-trigger .hover-target {
    display: none;
}

.hover-trigger:hover .hover-target {
    display: block;
    padding-left: 6px
}
</style>
       

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAppV7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <script src="https://js.stripe.com/v3/"></script>
    <script src="https://cdn.jsdelivr.net/npm/alpine-turbo-drive-adapter@1.0.x/dist/alpine-turbo-drive-adapter.min.js" defer></script>
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/tom-select/dist/js/tom-select.complete.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/autosize.js/4.0.2/autosize.min.js"></script>
    <script src="https://kit.fontawesome.com/1301feaea8.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <main class="">
      <p class="notice"><%#= notice %></p>
      <p class="alert"><%#= alert %></p>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<% content_for :side_navbar do %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %>
  <%= render partial: "application/side_navbar" %>
<% end %>

<% content_for :project_content do %>
  <%= render partial: "application/project_content" %>
<% end %>

<% content_for :content_list do %>
  <%= render partial: "application/content_list" %>
<% end %>


<%= render "basic_layout" %>

app/views/pages/people.html.erb
<% content_for :side_navbar do %>
  <%= render partial: "application/side_navbar" %>
<% end %>

<% content_for :project_content do %>
  <%= render partial: "application/project_content" %>
<% end %>

<% content_for :content_list do %>
  <%= render partial: "application/content_list" %>
<% end %>

<%= render "basic_layout" %>

app/views/projects/_form.html.erb
<%= form_with(model: project, class: "contents") do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :project_name %>
    <%= form.text_field :project_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<%= link_to project do %>
<div class="bg-teal-dark py-1">
  <%= project.project_name %>
</div>

<% end %>

<!-- <div id="<%#= dom_id project %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Project name:</strong>
    <%#= project.project_name %>
  </p>

  <%# if action_name != "show" %>
    <%#= link_to "Show this project", project, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%#= link_to 'Edit this project', edit_project_path(project), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <%# end %>
</div> -->

app/views/projects/_projects_sidebar.html.erb
<% @projects.each do |project| %>
  <%= link_to project_path do %>
    <div class="bg-teal-dark py-1 px-6 hover:bg-gray-200 ">
      <%= project.project_name %>
    </div>
  <% end %>
<% end %>

<!-- <div id="<%#= dom_id project %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Project name:</strong>
    <%#= project.project_name %>
  </p>

  <%# if action_name != "show" %>
    <%#= link_to "Show this project", project, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%#= link_to 'Edit this project', edit_project_path(project), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <%# end %>
</div> -->

app/views/projects/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing project</h1>

  <%= render "form", project: @project %>

  <%= link_to "Show this project", @project, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to projects", projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/projects/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Projects</h1>
    <%= link_to 'New project', new_project_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="projects" class="min-w-full">
    <%= render @projects %>
  </div>
</div>


<% if user_signed_in? %>
  <% content_for :side_navbar do %>
    <%= render partial: "application/side_navbar" %>
  <% end %>

  <% content_for :project_content do %>
    <%= render partial: "application/project_content" %>
  <% end %>

  <% content_for :content_list do %>
    <%= render partial: "application/content_list" %>
  <% end %>
<% end %>

<%= render "basic_layout" %>

app/views/projects/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New project</h1>

  <%= render "form", project: @project %>

  <%= link_to 'Back to projects', projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/projects/show.html.erb
<!-- <div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%#= render @project %>

    <%#= link_to 'Edit this project', edit_project_path(@project), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%#= button_to 'Destroy this project', project_path(@project), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%#= link_to 'Back to projects', projects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div> -->

<% content_for :side_navbar do %>
  <%= render partial: "application/side_navbar" %>
<% end %>

<% content_for :project_content do %>
  <%= render partial: "application/project_content" %>
<% end %>

<% content_for :content_list do %>
  <%= render partial: "application/content_list" %>
<% end %>

<%= render "basic_layout" %>

app/views/subprojects/_form.html.erb
<%= form_with(model: [@subproject.project, @subproject], class: "contents") do |form| %>
  <% if subproject.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(subproject.errors.count, "error") %> prohibited this subproject from being saved:</h2>

      <ul>
        <% subproject.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :subproject_name %>
    <%= form.text_field :subproject_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/subprojects/_subproject.html.erb
<!-- <div id="<%#= dom_id subproject %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Subproject name:</strong>
    <%#= subproject.subproject_name %>
  </p>

  <%# if action_name != "show" %>
    <%#= link_to "Show this subproject", subproject, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%#= link_to 'Edit this subproject', edit_subproject_path(subproject), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <%# end %>
</div> -->

<!-- Content item(s) -->
<div class="flex items-start mb-6 text-sm" id="<%= dom_id subproject %>">
  <div class="flex-1 overflow-hidden">
      <div>
          <span class="font-bold text-xl ml-10"><%= subproject.subproject_name %></span>
      </div>
      <div class="flex items-start mt-2">
        <div class="flex items-center">
          <div class="relative flex items-center justify-center flex-shrink-0 w-8 h-8 mr-2 mb-4 md:mb-6 overflow-hidden bg-gray-50 rounded">
              <i class="fa fa-solid fa-grip-vertical fa-lg"></i>
            </div>
            <div class="w-10 h-12">
              <div class="round">
                  <input type="checkbox" checked id="checkbox" />
                  <label for="checkbox"></label>
              </div>
            </div>
        </div>
        <div class="flex-1 overflow-hidden">
            <p class="text-black leading-normal">VPN connection</p>
        </div>
    </div>
    <div class="flex items-start">
      <div class="flex">
          <div class="w-8 mr-2">
        </div>                         
         <div class="w-10 border-b">
         </div>
        </div>
        <div class="flex-1 overflow-hidden border-b">
        </div>
    </div>
    <div class="flex items-start mt-2">
      <div class="flex items-center">
        <div class="relative flex items-center justify-center flex-shrink-0 w-8 h-8 mr-2 mb-4 md:mb-6 overflow-hidden bg-gray-50 rounded">
            <i class="fa fa-solid fa-grip-vertical fa-lg"></i>
          </div>
        <div class="w-10 h-12">
          <div class="round">
              <input type="checkbox" checked id="checkbox" />
              <label for="checkbox"></label>
          </div>
      </div>
    </div>
    <div class="flex-1 overflow-hidden">
        <p class="text-black leading-normal">Need to create a ticket for the New API documnetation is reviewed by DevX team and published on our wesbite.</p>
    </div>
  </div>
  <div class="flex items-start">
    <div class="flex">
      <div class="w-8 mr-2">
      </div>                         
      <div class="w-10 border-b">

      </div>
    </div>
    <div class="flex-1 overflow-hidden border-b">
    </div>
  </div>
    <div class="pb-6 pl-10 flex-none mt-2">
        <div class="flex rounded-lg border-2 border-grey overflow-hidden">
            <div class="focus:outline-none py-2">
                <input class="w-full px-4 focus:outline-none mb-13" placeholder="New item">
                <input class="w-full px-4 focus:outline-none mb-2" placeholder="Description" />

                <button class="ml-4 p-1 pl-2 pr-2 focus:outline-none bg-white border-2 text-sm rounded-md">
                    <i class="fa-regular fa-calendar"></i>
                    <span>Today</span>
                </button>
                <button class="ml-1 p-1 pl-2 pr-2 focus:outline-none bg-white border-2 text-sm rounded-md">
                    <i class="fa-regular fa-flag"></i>
                    <span>Priority</span>
                </button>
                <button class="ml-1 p-1 pl-2 pr-2 focus:outline-none bg-white border-2 text-sm rounded-md">
                    <i class="fa-regular fa-clock"></i>
                    <span>Reminder</span>
                </button>

                <!-- <input type="search" placeholder="Search" class="ml-4 appearance-none border focus:outline-none border-grey rounded-lg pr-4 py-2"> -->
            </div>
        </div>
    </div>
  </div>
</div>

app/views/subprojects/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing subproject</h1>

  <%= render "form", subproject: @subproject %>

  <%= link_to "Show this subproject", @subproject, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to subprojects", subprojects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/subprojects/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Subprojects</h1>
    <%= link_to 'New subproject', new_subproject_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="subprojects" class="min-w-full">
    <%= render @subprojects %>
  </div>
</div>

app/views/subprojects/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New subproject</h1>

  <%= render "form", subproject: @subproject %>

  <%= link_to 'Back to subprojects', project_subprojects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/subprojects/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @subproject %>

    <%= link_to 'Edit this subproject', edit_subproject_path(@subproject), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this subproject', subproject_path(@subproject), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to subprojects', subprojects_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>